[ism_problems_input://awan_test_problems]
interval = 65
parameters = %24filter%3D%28Status%20ne%20%27resolved%27%29

[ism_service_requests_input://awan_test_srs]
interval = 60
parameters = %24filter%3DStatus%20ne%20%27Fulfilled%27%20and%20Status%20ne%20%27Cancelled%27%20and%20Status%20ne%20%27Closed%27
